version: "3"

services:
  mongodb:
    image: mongo
    ports:
      - 37017:27017

  backend:
    build:
      context: backend
      dockerfile: Dockerfile.local
    ports:
      - 4000:4000
    volumes:
      - ./backend/src:/app/src
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.local
    ports:
      - 3000:3000
    volumes:
      - ./frontend/public:/app/public
      - ./frontend/src:/app/src
    env_file:
      - ./frontend/.env
