FROM node:18-alpine3.16

RUN apk add g++ make python3

WORKDIR /app

ADD package.json package-lock.json tsconfig.json nodemon.json ./

RUN npm install --legacy-peer-deps

RUN npm rebuild bcrypt --build-from-source

CMD [ "npm", "run", "dev" ]
